networks:
  demoappnetowrk: 

services:
 mssql-container:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql-container
    environment:
      - ACCEPT_EULA=Y   # Accept the End-User License Agreement
      - SA_PASSWORD=MyDemoPassword@2022 # Set the 'sa' user password
    ports:
     - "8002:1433"
    networks:
        - demoappnetowrk
 airsense.api:
    image: ${DOCKER_REGISTRY-}airsenseapi
    build:
      context: .
      dockerfile: AirSense.Api/Dockerfile
    depends_on:
    - mssql-container
    networks:
        - demoappnetowrk
